import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/dashboard.tsx"),
  route("login", "routes/login.tsx"),
  route("set-locale", "routes/set-locale.ts"),
  route("auth/callback", "routes/auth.callback.tsx"),
  route("logout", "routes/logout.tsx"),
  route(
    "dashboard/details/:detailKind/:detailId",
    "routes/dashboard.details.$detailKind.$detailId.ts",
  ),
  route("health", "routes/api.health.ts"),
  route("metrics", "routes/api.metrics.ts"),
  route("api/v1/token", "routes/api.token.ts"),
  route("api/v1/send", "routes/api.send.ts"),
  route("api/v1/config", "routes/api.config.ts"),
  route("api/v1/jobs", "routes/api.jobs.ts"),
  route("api/v1/jobs/delivery-status", "routes/api.jobs.delivery-status.ts"),
  route("api/v1/jobs/:jobId", "routes/api.jobs.$jobId.ts"),
  route("api/v1/jobs/:jobId/delivery-status", "routes/api.jobs.$jobId.delivery-status.ts"),
  route("api/v1/jobs/:jobId/pause", "routes/api.jobs.$jobId.pause.ts"),
  route("api/v1/jobs/:jobId/resume", "routes/api.jobs.$jobId.resume.ts"),
  route("api/v1/jobs/:jobId/retry", "routes/api.jobs.$jobId.retry.ts"),
  route("api/v1/applications", "routes/api.applications.ts"),
  route("api/v1/configs", "routes/api.configs.ts"),
  route("api/v1/configs/:configId", "routes/api.configs.$configId.ts"),
  route("api/v1/configs/:configId/validate", "routes/api.configs.$configId.validate.ts"),
  route("api/v1/configs/:configId/tokens", "routes/api.configs.$configId.tokens.ts"),
  route("api/v1/tokens/:tokenId/revoke", "routes/api.tokens.$tokenId.revoke.ts"),
  route("api/v1/tokens/:tokenId/rotate", "routes/api.tokens.$tokenId.rotate.ts"),
  route("api/v1/tokens/:tokenId/scopes", "routes/api.tokens.$tokenId.scopes.ts"),
  route("api/v1/tokens/:tokenId", "routes/api.tokens.$tokenId.ts"),
  route("api-failures", "routes/dashboard.api-failures.tsx"),
] satisfies RouteConfig;
